```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(gt)
library(tsibble)
```


```{r}
hr <- read_csv("data/HRDataset_v13.csv") %>% 
  clean_names()
```
```{r}
# cleaning column names
hr <- hr %>% 
  rename(c("date_of_hire" = "dateof_hire", "date_of_termination" = "dateof_termination", "days_late_last_30" = "days_late_last30"))
```

```{r}
# converting data to lower case as dataframe utilises nconsistent capitalisation
hr <- data.frame(lapply(hr, function(x){
  if (is.character(x)) return(tolower(x))
  else return(x)
}))
hr <- hr %>% 
  mutate_if(is.factor, as.character)
```

```{r}
# percentage of respondents who identify as hispanic and/or latino`
hispanic_latino_percentage <- hr %>% group_by(hispanic_latino) %>% 
  filter(!is.na(hispanic_latino)) %>% 
 count()
round(hispanic_latino_percentage[2,2]/ hispanic_latino_percentage[1,2] * 100, digits = 2)
```
```{r}
 hr %>% group_by(race_desc) %>% 
  filter(!is.na(race_desc)) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) 
```
There were a total of 29 hires from diversity job fairs, all were from ethnic minorities. 
```{r}
hr %>% 
  select(race_desc, hispanic_latino, from_diversity_job_fair_id) %>% 
  filter(from_diversity_job_fair_id == 1)
```
```{r}
hr %>% 
  select(race_desc, hispanic_latino, recruitment_source) %>% 
  filter(!is.na(recruitment_source)) %>%
  filter(recruitment_source != "other") %>% 
  group_by(recruitment_source) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n))
```
```{r}
hr %>% 
  select(race_desc, hispanic_latino, recruitment_source) %>% 
  filter(!is.na(recruitment_source)) %>%
  filter(recruitment_source != "other") %>% 
  filter(race_desc == "white") %>% 
  group_by(recruitment_source) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n))
```
```{r}
hr %>% 
  select(race_desc, hispanic_latino, recruitment_source) %>% 
  filter(!is.na(recruitment_source)) %>%
  filter(recruitment_source != "other") %>% 
  filter(race_desc != "white") %>% 
  group_by(recruitment_source) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n))
```
```{r}
median(hr$emp_satisfaction)
```

```{r}
# calculating the percentage of employees who are not fully meeting their performance requirements 
valid_rows <- sum(!is.na(hr$performance_score)) 

fully_meets <- hr %>% 
  filter(performance_score != "fully meets") %>% 
  count()/valid_rows * 100
exceeds <- hr %>% 
  filter(performance_score != "exceeds") %>% 
  count()/valid_rows * 100

pip <- hr %>% 
  filter(performance_score == "pip") %>% 
  count()/valid_rows * 100

needs_improvement <- hr %>% 
  filter(performance_score == "needs improvement") %>% 
  count()/valid_rows * 100

fully_meets + exceeds + pip + needs_improvement

```

# The president and CEO makes more than 4x that of the lowest paid position. 
```{r}
hr %>% 
  group_by(position) %>% 
  summarise(n = mean(pay_rate)) %>% 
  arrange(desc(n))
```
```{r}
# As the vast majority of employees where location is known are based in Massachusetts little analysis can be done about location
hr %>% 
  group_by(state) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n))
```
```{r}
hr %>% 
  filter(term_reason == "n/a - still employed") %>% 
  nrow()
```
```{r}
hr %>% 
  filter(term_reason == "n/a - has not started yet") %>% 
  nrow()
```

```{r}
have_left <- hr %>% 
   filter(!is.na(term_reason)) %>% 
  filter(term_reason != "n/a - still employed") %>% 
  filter(term_reason != "n/a - has not started yet")
have_left
```
```{r}
# establishing baseline 
total_positions <- hr %>% 
  count(position) %>% 
  arrange(desc(n))
```

```{r}
positions_left <- have_left %>% 
count(position) %>% 
  arrange(desc(n))
```

```{r}
right_join(total_positions, positions_left, by = c("position" = "position")) %>%
  rename("total" = "n.x", "have_left" = "n.y") %>% 
  mutate(percentage = round(have_left/total * 100, digits = 2))
```
```{r}
# establishing baseline 
total_race_desc <- hr %>% 
  count(race_desc) %>% 
  arrange(desc(n))
```

```{r}
race_desc_left <- have_left %>% 
count(race_desc) %>% 
  arrange(desc(n))
```

```{r}
right_join(total_race_desc, race_desc_left, by = c("race_desc" = "race_desc")) %>%  rename("total" = "n.x", "have_left" = "n.y") %>% 
 mutate(percentage = round(have_left/total * 100, digits = 2))
```
```{r}
# establishing baseline 
total_sex_split <- hr %>% 
  count(sex) %>% 
  arrange(desc(n))
```

```{r}
sex_split_left <- have_left %>% 
count(sex) %>% 
  arrange(desc(n))
```

```{r}
right_join(total_sex_split, sex_split_left, by = c("sex" = "sex")) %>%
  rename("total" = "n.x", "have_left" = "n.y") %>% 
  mutate(percentage = round(have_left/total * 100, digits = 2))
```

```{r}
# establishing baseline 
total_dept <- hr %>% 
  count(department) %>% 
  arrange(desc(n))
```

```{r}
dept_left <- have_left %>% 
count(department) %>% 
  arrange(desc(n))
```

```{r}
right_join(total_dept, dept_left, by = c("department" = "department")) %>%
  rename("total" = "n.x", "have_left" = "n.y") %>% 
  mutate(percentage = round(have_left/total * 100, digits = 2))
```

```{r}
hr_function <- function(set, subset){
  total_employees <- set %>% count(set$sex)
  employees_left <- subset %>% count(subset$sex)
  
  right_join(total_employees, employees_left, by = c("sex" = "sex")) %>%
  rename("total" = "n.x", "have_left" = "n.y") %>% 
  mutate(percentage = round(have_left/total * 100, digits = 2))
}
```

```{r}
total_employees <- hr %>% count(hr$sex)
employees_left <- have_left %>% count(have_left$sex)
```
```{r}
terminated_for_cause <- hr %>% 
  filter(employment_status == "terminated for cause") 
```
```{r}
terminated_for_cause %>% 
  filter(!is.na(emp_satisfaction)) %>% 
  summarise(mean(emp_satisfaction)) %>% 
  round(digits = 2)
```
```{r}
have_left  %>% 
  filter(!is.na(emp_satisfaction)) %>% 
  summarise(mean(emp_satisfaction)) %>% 
  round(digits = 2)
```

```{r}
hr %>% 
  filter(!is.na(emp_satisfaction)) %>% 
  summarise(mean(emp_satisfaction)) %>% 
  round(digits = 2)
```
```{r}
terminated_for_cause %>% 
  filter(!is.na(perf_score_id)) %>% 
  summarise(mean(perf_score_id)) %>% 
  round(digits = 2)
```
```{r}
have_left  %>% 
  filter(!is.na(perf_score_id)) %>% 
  summarise(mean(perf_score_id)) %>% 
  round(digits = 2)
```

```{r}
hr %>% 
  filter(!is.na(perf_score_id)) %>% 
  summarise(mean(perf_score_id)) %>% 
  round(digits = 2)
```
```{r}
# finding the mode employee satisfaction score

getmode <- function(v){
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}
result <- getmode(hr$emp_satisfaction)
print(result)
```








